SUBGENRE_TO_MAIN = {
    "Acoustic Folk": "Country",
    "Acoustic Pop": "Pop",
    "Acoustic Pop Ballad": "Pop",
    "Afro-Cuban Jazz": "Jazz",
    "Afrobeats Pop": "Pop",
    "Alternative Electronic Rock": "Rock",
    "Alternative Hip-Hop": "Hip-Hop",
    "Alternative Metal": "Rock",
    "Alternative Pop": "Rock",
    "Alternative Pop Rock": "Rock",
    "Alternative R&B": "R&B",
    "Alternative Rock": "Rock",
    "Alternative Rock Acoustic": "Rock",
    "Alternative Rock Ballad": "Rock",
    "Ambient Classical": "Classical",
    "Ambient Pop": "Pop",
    "Arena Rock": "Rock",
    "Art Rock": "Rock",
    "Baroque Pop": "Pop",
    "Beat Pop": "Pop",
    "Bedroom Pop": "Pop",
    "Big Beat": "Electronic",
    "Big Room House": "Electronic",
    "electronic": "Electronic",
    "Blue-Eyed Soul": "R&B",
    "Blues Rock": "Rock",
    "Bollywood Comedy Song": "Pop",
    "Bollywood Dance Pop": "Pop",
    "pop": "Pop",
    "Bollywood Folk Dance": "Electronic",
    "Bollywood Indie Pop": "Pop",
    "Bollywood Rock": "Rock",
    "Bollywood Rock and Roll": "Rock",
    "Britpop": "Pop",
    "Cabaret Dance": "Electronic",
    "Classic Rock": "Rock",
    "Classical": "Classical",
    "classical": "Classical",
    "Cool Jazz": "Jazz",
    "Country": "Country",
    "Country Ballad": "Country",
    "Country Dance": "Country",
    "Country Folk": "Country",
    "Country Patriotic": "Country",
    "Country Pop": "Country",
    "Country Pop Ballad": "Country",
    "Country Rap": "Hip-Hop",
    "Country Rock": "Country",
    "Country Soul": "R&B",
    "Dance Pop": "Pop",
    "Dance Rock": "Rock",
    "rock": "Rock",
    "Dark Pop": "Pop",
    "Disco": "R&B",
    "r&b": "R&B",
    "Disco Funk": "R&B",
    "Disco Pop": "Pop",
    "Disco Soul": "R&B",
    "Dream Pop": "Pop",
    "Dubstep": "Electronic",
    "EDM Trap": "Electronic",
    "Electro House": "Electronic",
    "Electronic": "Electronic",
    "Electronic Dance": "Electronic",
    "Electronic Dance Pop": "Electronic",
    "Electronic Pop": "Electronic",
    "Electropop": "Electronic",
    "Film Pop Ballad": "Pop",
    "Folk EDM": "Electronic",
    "Folk Fusion": "Country",
    "Folk Pop": "Pop",
    "Folk Rock": "Rock",
    "Funk": "R&B",
    "Funk Pop": "R&B",
    "Funk Rock": "R&B",
    "Garage Rock": "Rock",
    "Glam Metal Ballad": "Rock",
    "Gospel Pop": "R&B",
    "Gothic Rock": "Rock",
    "Groove Metal": "Rock",
    "Grunge": "Rock",
    "Grunge Rock": "Rock",
    "Gujarati Folk Fusion": "Country",
    "Hard Bop": "Jazz",
    "Hard Rock": "Rock",
    "Hard Rock Ballad": "Rock",
    "Hardcore Hip-Hop": "Hip-Hop",
    "Heartland Rock": "Rock",
    "Heavy Metal": "Rock",
    "Heavy Metal Ballad": "Rock",
    "Hindu Devotional": "Classical",
    "Hip-Hop": "Hip-Hop",
    "Hip-Hop R&B": "R&B",
    "Hip-Hop Soul": "R&B",
    "Indian Classical": "Classical",
    "Indian Classical Ghazal": "Classical",
    "Indian Classical Thumri": "Classical",
    "Indian Film Acoustic Ballad": "Pop",
    "Indian Film Acoustic Rock Ballad": "Rock",
    "Indian Film Classical Ballad": "Classical",
    "Indian Film Devotional Pop": "Classical",
    "Indian Film Devotional Romantic": "Classical",
    "Indian Film Feel-Good Pop": "Pop",
    "Indian Film Folk Ballad": "Country",
    "Indian Film Friendship Ballad": "Pop",
    "Indian Film Ghazal": "Classical",
    "Indian Film Patriotic Rock": "Rock",
    "Indian Film Philosophical Ballad": "Classical",
    "Indian Film Philosophical Song": "Classical",
    "Indian Film Romantic Ballad": "Pop",
    "Indian Film Romantic Duet": "Pop",
    "Indian Film Sad Ballad": "Classical",
    "Indian Film Sufi Ballad": "Classical",
    "Indian Film Travel Ballad": "Pop",
    "Indian Film Travel Pop": "Pop",
    "Indian Folk": "Country",
    "Indian Folk Pop": "Country",
    "Indian Indie Folk": "Country",
    "Indian Indie Pop": "Pop",
    "Indian Indie Rock": "Rock",
    "Indian Indie Romantic": "Pop",
    "Indian Indie Romantic Ballad": "Pop",
    "Indian Patriotic Ballad": "Classical",
    "Indian Patriotic Song": "Country",
    "Indie Electronic": "Electronic",
    "Indie Folk": "Country",
    "Indie Folk Pop": "Country",
    "Indie Folk Rock": "Country",
    "Indie Pop": "Pop",
    "Indie Pop Acoustic": "Pop",
    "Indie Rock": "Rock",
    "Indie Romantic Pop": "Pop",
    "Indie Soul": "R&B",
    "Indo-Pop Dance": "Electronic",
    "Jazz Ballad": "Jazz",
    "Modern Jazz" : "Jazz",
    "Jazz Funk": "Jazz",
    "Jazz Fusion": "Jazz",
    "Jazz Rap": "Jazz",
    "Jazz Standard": "Jazz",
    "Jazz Vocal": "Jazz",
    "Jazz Waltz": "Jazz",
    "Latin Pop": "Pop",
    "Marathi Folk Dance": "Country",
    "Marathi Romantic Ballad": "Classical",
    "Minimalist Pop": "Pop",
    "Modal Jazz": "Jazz",
    "Motown Soul": "R&B",
    "Neo-Soul": "R&B",
    "Neo-Soul Funk Pop": "R&B",
    "New Wave Pop": "Pop",
    "Nu Metal": "Rock",
    "Patriotic Country": "Country",
    "Pop": "Pop",
    "Rock": "Rock",
    "Pop Anthem": "Pop",
    "Semi-Classical": "Classical",
    "Pop Ballad": "Pop",
    "Pop Folk": "Country",
    "Ghazal": "Classical",
    "Pop Funk": "R&B",
    "Pop Gospel": "R&B",
    "Pop Punk": "Rock",
    "Pop R&B": "R&B",
    "Pop Rap": "Hip-Hop",
    "Pop Rock": "Rock",
    "Pop Rock Ballad": "Rock",
    "Pop Soul": "R&B",
    "Pop Soul Ballad": "R&B",
    "Post-Disco": "R&B",
    "Power Ballad Rock": "Rock",
    "Progressive House": "Electronic",
    "Progressive Pop": "Electronic",
    "Progressive Rock": "Rock",
    "Psychedelic Pop": "Rock",
    "Psychedelic Rock": "Rock",
    "Psychedelic Soul": "R&B",
    "Punjabi Folk Dance": "Country",
    "Punjabi Folk Pop": "Country",
    "Punjabi Pop": "Pop",
    "Punk Rock": "Rock",
    "R&B": "R&B",
    "R&B Pop": "R&B",
    "R&B Soul": "R&B",
    "Rajasthani Folk": "Country",
    "Rajasthani Folk Dance": "Country",
    "Rajasthani Folk Pop": "Country",
    "Rap Metal": "Hip-Hop",
    "Rap Rock": "Hip-Hop",
    "Reggae": "R&B",
    "Reggae Fusion": "R&B",
    "Retro Pop": "Pop",
    "Retro Soul": "R&B",
    "Rock Ballad": "Rock",
    "Rock and Roll": "Rock",
    "Rockabilly": "Country",
    "Roots Rock": "Country",
    "Smooth Jazz": "Jazz",
    "Jazz": "Jazz",
    "Soft Rock": "Rock",
    "Soft Rock Ballad": "Rock",
    "Soul": "R&B",
    "Soul Jazz": "Jazz",
    "Soul Pop": "R&B",
    "Soul Pop Ballad": "R&B",
    "Southern Rock": "Country",
    "Speed Metal": "Rock",
    "Sufi Devotional": "Classical",
    "Christian Devotional": "Classical",
    "Sufi Pop": "Classical",
    "Sacred Classical": "Classical",
    "Sufi Rock": "Classical",
    "Sufi Romantic": "Pop",
    "Swing Jazz": "Jazz",
    "Synth Pop": "Pop",
    "Synthwave Pop": "Pop",
    "Telugu Folk Dance": "Country",
    "Thrash Metal": "Rock",
    "Traditional Pop": "Pop",
    "Trap Hip-Hop": "Hip-Hop",
    "Trap Pop": "Pop",
    "Trip Hop": "Electronic",
    "Tropical House": "Electronic",
    "Tropical Pop": "Pop",
    "Vocal Jazz": "Jazz",
    "West Coast Hip-Hop": "Hip-Hop",
    "Worldbeat": "Electronic"
}

def map_to_main_genre(genre: str):
    return SUBGENRE_TO_MAIN[genre]  # will raise error if any genre is missing
